@Library("shared-library")_
pipeline {
    agent any
    
    tools{
        nodejs 'nodejs'
    }
    
    environment {
        PROJECT_ROOT = 'ProyectoNode'
        REGISTRY = 'priscillajb/nodeapp'
    }
    
    stages{


    	stage('Build'){
            steps{
                Build(project_root:PROJECT_ROOT,registry:REGISTRY,buildNumber:"${BUILD_NUMBER}")
            }
    }
}
}